// Шрифт для эмулятора Radio-86RK в JavaScript
//
// Copyright (C) 2012 Александр Демин <alexander@demin.ws>
//
// Эта программа является свободным программным обеспечением; Вы можете распространять его и / или изменять
// это в соответствии с условиями GNU General Public License, опубликованной
// Фонд свободного программного обеспечения; либо версия 2, либо (по вашему выбору)
// любая более поздняя версия.
//
// Эта программа распространяется в надежде, что она будет полезна,
// но БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ; даже без подразумеваемой гарантии
// ТОРГОВЛЯ или пригодность для особой цели. Увидеть
// GNU General Public License для более подробной информации.
//
// Вы должны были получить копию Стандартной общественной лицензии GNU
// вместе с этой программой; если нет, напишите в свободное программное обеспечение
// Foundation, Inc., 59 Temple Place - Suite 330, Бостон, MA 02111-1307, США.

function rk86_font_image () {return 'data: image / bmp; base64,' +
'Qk0 + IAAAAAAAAD4AAAAoAAAACAAAAAAIAAABAAEAAAAAAAAgAAAAAAAAAAAAA' + 
'AAAAAAAAAAAAAAAAP /// wAAAAAAGAAAABgAAAB + AAAAfgAAABgAAAAYAAAA' + 
'AAAAAAAAAABAAAAAQAAAA8AAAAJAAAACQAAAAAAAAAAAAAAAQAAADAAAAAq' + 
'AAAAKgAAACoAAAAqAAAAAAAAAAAAAAAAAAAADgAAAAEAAAAHAAAAAQAAAA4A' + 
'AAAAAAAAAAAAAAAAAAfAAAAFQAAABUAAAAVAAAAFQAAAAAAAAAAAAAAAAAA' + 
'AA4AAAABAAAAAgAAAAkAAAAGAAAAAAAAAAAAAAAAAAAAGQAAABUAAAAZAAAA' + 
'EQAAABEAAAAAAAAAAAAAAAAAAAAOAAAACQAAAA4AAAAIAAAACAAAAAAAAAAAA' + 
'AAAAAAAAA4AAAAJAAAADgAAAAkAAAAOAAAAAAAAAAAAAAAAAAAAFQAAABUA' + 
'AAAOAAAAFQAAABUAAAAAAAAAAAAAAAAAAAAOAAAAAQAAAAcAAAAJAAAACQAA' + 
'AAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAfAAAAAAAAAAAAAAAAAAAA' + 
'BwAAAgAAAAIAAAACAAAAAcAAAAAAAAAAAAAAAgAAAAIAAAACAAAAA4AAAAJ' + 
'AAAADgAAAAAAAAAAAAAAAAAAAAkAAAAFAAAABwAAAAkAAAAHAAAAAAAAAAAAA + + 
'AAAAAAAACQAAAAkAAAAJAAAACQAAAA8AAAAAAAAAAAAAAAAAAAAGAAAACQAA' + 
'AAkAAAJAAAABgAAAAAAAAAAAAAAAAAAAAkAAAAJAAAADADAAAAkAAAAJAAAA' + 
'AAAAAAAAAAAAAAAEQAAABUAAAAVAAAAGwAAABEAAAAAAAAAAAAAAAAAAAAJJ' + 
'AAAACQAAAAkAAAAFAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAKAAAADAAAAAoA' + 
'AAAJAAAAAAAAAAAAAAAAAAACQAAAA0AAAALAAAACQAAAAkAAAAAAAAABgAA' + 
'AAAAAAAAAAADQAAAAsAAAAJAAAACQAAAAAAAAAAAAAAAAAAAAkAAAAJAAAA' + 
'BgAAAAYAAAAJAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAACAAAAA8AAAAA' + 
'AAAAAAAAAAQAAAEAAAADgAAABUAAAAOAAAABAAAAAAAAAAAAAAAAAAAAAcA' + 
'AAAIAAAADgAAAAkAAAAGAAAAAAAAAAAAAAAAAAAADwAAAAEAAAAHAAAACQAA' + 
'AAYAAAAAAAAAAAAAAAEAAAAfAAAAEgAAABIAAAASAAAAEgAAAAAAAAAAAAAAA' + 
'AAAAAA4AAAAJAAAADgAAAAgAAAAHAAAAAAAAAAAAAAAAAAAABgAAAAkAAAAH' + 
'AAAAAQAAAA4AAAAAAAAAAAAAAAAAAAASAAAAFQAAAB0AAAAVAAAAEgAAAAAA' + 
'AAAAAAAAAAAAAQAAAAMAAAAHgAAAD8AAAAeAAAADAAAAAgAAAAAAAAAAQAA' + 
'AAMAAAAPAAAADAAAAAgAAAAAAAAAAAAAAAAAAAARAAAACAAAAAgAAAAEAAAA' + 
'CAAAAAgAAAAQAAAAAAAAAAgAAAAIAAAACAAAAAAAAAAIAAAACAAAAAgAAAAAA' + 
'AAAAAQAAAAIAAAACAAAABAAAAAIAAAACAAAAAQAAAAAAAAAPAAAACAAAAAYA' + 
'AAABAAAADwAAAAAAAAAAAAAAAAAAAA4AAAABAAAABwAAAAkAAAAJAAAAAAAAA' + 
'AAAAAAAAAAAEQAAAAoAAAACAAAACgAAABEAAAAAAAAAAAAAAAAAAAAKAAAAA + + 
'FQAAABUAAAARAAAAEQAAAAAAAAAAAAAAAAAAAAQAAAAKAAAAEQAAABEAAAAR' + 
'АААААААААААААААААААДГАААБЕАААРААААЕКАААБЕАААААААААААААААА' + 
'AAAGAAAACQAAAAgAAAAIAAAAHAAAAAgAAAAIAAAAAAAAAA4AAAABAAAABgAA' + 
'AAgAAAHAHAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAACQAAAA4AAAAAAAAA' + 
'AAAAAAAAAABAAAABwAAAAkAAAAJAAAABwAAAAAAAAAAAAAAAAAAAAgAAAAO' + 
'AAAACQAAAAkAAAAOAAAAAAAAAAAAAAAAAAAABgAAAAkAAAAJAAAACQAAAAYA' + 
'AAAAAAAAAAAAAAAAAAJAAAACQAAAAkAAAAJAAAADgAAAAAAAAAAAAAAAAAA' + 
'ABUAAAAVAAAAFQAAABUAAAAaAAAAAAAAAAAAAAAAAAAABwAAAAIAAAACAAAA' + 
'AgAAAAIAAAACAAAABgAAAAAAAAAJAAAACgAAAAwAAAAKAAAACQAAAAgAAAAI' + 
'AAAAAAAAAYAAAAJAAAAAQAAAAEAAAABAAAAAAAAAAEAAAAAAAAABwAAAAIA' + 
'AAACAAAAAgAAAAYAAAAAAAAAAgAAAAAAAAAJAAAACQAAAAkAAAAJAAAADgAA' + 
'AAgAAAIAAAAAAAAAA4AAAABAAAABwAAAAkAAAAHAAAAAAAAAAAAAAAAAAAAA' + 
'CAAAAAgAAAAIAAAAHAAAAAgAAAAJAAAABgAAAAAAAAAHAAAACAAAAA4AAAAJJ' + 
'AAAABgAAAAAAAAAAAAAAAAAAAAcAAAAJAAAACQAAAAkAAAAHAAAAAQAAAAEA' + 
'ААААААААБАААААГАААИААААААААААААААААААААААААААААОААААККАА' + 
'AAkAAAAAAAADgAAAAgAAAAIAAAAAAAAAA0AAAASAAAAEgAAABIAAAAOAAAA' + 
'АААААААААААААААААААААААААААААААААААААААААААААААААААААААЕ' + 
'AAAAAAAAAAQAAACAAAAAQAAABEAAAAOAAAAAAAAAAgAAAAEAAAAAgAAAAEAEA + + 
'АААКААААБАААААГААААААААААААААААААААфАААААААААБ8ААААААААААААА' + 
'AAAAAAACAAAABAAAAAgAAAAQAAAACAAAAAQAAAACAAAAAAAAAAgAAAAEAAAA' + 
'DAAAAAwAAAAAAAAADAAAAAwAAAAAAAAADAAAAAwAAAAAAAAAAAAAAAwAAAAM' + 
'AAAAAAAAAAAAAAcAAAAAgAAAAEAAAAPAAAAEQAAABEAAAAOAAAAAAAAAA4A' + 
'AAARAAAAEQAAAA4AAAARAAAAEQAAAA4AAAAAAAAACAAAAAgAAAAIAAAABAAA' + 
'AAIAAAABAAAAHwAAAAAAAAAOAAAAEQAAABEAAAAeAAAAEAAAAAgAAAAHAAAA' + 
'AAAAAA4AAAARAAAAAQAAAAEAAAAeAAAAEAAAAB8AAAAAAAAAAgAAAAIAAAAf' + 
'AAAAEgAAAAoAAAAGAAAAAgAAAAAAAAAOAAAAEQAAAAEAAAAGAAAAAgAAAAEAEA + + 
'AAAfAAAAAAAAB8AAAAQAAAACAAAAAYAAAABAAAAEQAAAA4AAAAAAAAADgAA' + 
'AAQAAAAEAAAABAAAAAQAAAAMAAAABAAAAAAAAAAOAAAAEQAAABkAAAAVAAAA' + 
'EwAAABEAAAAOAAAAAAAAAAAAAAAQAAAACAAAAAQAAAACAAAAAQAAAAAAAAAAA + + 
'ААААДАААААВАААААААААААААААААААААААААААААААААААААААААААААААА' + 
'AAAfAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAEAAAADAAAAAwAAAAAAAAAAAAA' + 
'AAAAAAAAAAAAAAAAAQAAAAEAAAAHwAAAAQAAAAEAAAAAAAAAAAAAAAAAAAA' + 
'BAAAABUAAAAOAAAAFQAAAAQAAAAAAAAAAAAAAAgAAAAEAAAAAgAAAAIAAAAC' + 
'AAAABAAAAAgAAAAAAAAAAgAAAAQAAAAIAAAACAAAAAgAAAAEAAAAAgAAAAAA' + 
'AAAAAAAAAAAAAAAAAAEAAAAAgAAAAYAAAAGAAAAAAAAAA0AAAASAAAAFQAA' + 
'AAwAAAAKAAAACgAAAAQAAAAAAAAAAwAAABMAAAAIAAAABAAAAAIAAAAZAAAA' + 
'GAAAAAAAAAEAEAAAHgAAAAUAAAAOAAAAFAAAAA8AAAAEAAAAAAAAAAoAAAAK' + 
'AAAAHwAAAAoAAAAfAAAACgAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoA' + 
'AAAKAAAACgAAAAAAAAAEAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAAAAA' + 
'ААААААААААААААААААААААААААААААААААААААААААААААААААААААААААА + + 
'AAAAAAAAAAAAAAAAAAAAAUAAAAFAAAABQAAAD0AAAAnAAAAIAAAACAAAAA44 + 
'AAAABAAAAAwAAAAdAAAAPwAAAD8AAAAdAAAADAAAAAQAAAAAAAAAAAAAAAAA' + 
'AAA / AAAAPwAAAAAAAAAAAAAAAAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAA' + 
'ААВААААМААААААААААААААААААААААААААААААААААААААААААААААААААА' + 
'ААААААААААААААААААААААААААААААААААААААААААААААААААААААААААА + + 
'AAAAAAAAAAAAAAAAAAAPwAAAD8AAAA / AAAAPwAAAD8AAAA / AAAAPwAAAD8A' + 
'AAA / AAAAPwAAAD8AAAA / AAAABwAAAAcAAAAHAAAABwAAAD8AAAA / AAAAPwAA' + 
'AD8AAAA4AAAAOAAAADgAAAA4AAAAPwAAAD8AAAA / AAAAPwAAAAAAAAAAAAAA' + 
'AAAAAAAAAA4AAAAOAAAADgAAAA4AAAAPwAAAD8AAAA / AAAAPwAAADgAAAA4' + 
'AAAAOAAAADgAAAAHAAAABwAAAAcAAAAHAAAAOAAAADgAAAA4AAAAOAAAADgA' + 
'AAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAAAAAAAAAAAAAAAAAAAAAA' + 
'AAwAAAAeAAAAPwAAAAwAAAAMAAAADAAAAAwAAAAMAAAACAAAAAwAAAAuAAAA' + 
'PwAAAD8AAAAuAAAADAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' + 
ААААААААААААААААААААААААААААААААААААААААААААААААААААААААДАААААВА + 
'AAAMAAAADAAAAAwAAAA / AAAAHgAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' + 
'AAAAAAAAAAAAAAAACEAAAASAAAADAAAAAwAAAAtAAAAPwAAAAwAAAAMAAAA' + 
'АААААААААААААААААААААААААААААААААААААААААААААВААААААБваААААААААХ' + 
'AAAAPwAAAD8AAAA / AAAAPwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcA' + 
'AAAHAAAABwAAAAcAAAAHAAAABwAAADgAAAA4AAAAOAAAADgAAAAHAAAABwAA' + 
'ААААААХААААААААААААААААААААААААААААААААААААААААААААА / АААА' + 
'PwAAAD8AAAA / AAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAHAAAABwAAAAcAAAAA' + 
'АААААААААААААААААААОААААДГАААА4ААААОААААААААААААААААААААААА' + 
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAA / AAAAPwAAAD8AAAA / AAAAPwAA' + 
'AD8AAAAAAAAAAAAAAEAAAABAAAAHwAAABEAAAARAAAAEQAAAAAAAAABAAAA' + 
'HwAAABUAAAAVAAAAFQAAABUAAAAVAAAAAAAAAA4AAAARAAAAAQAAAAcAAAAB' + 
'AAAAEQAAAA4AAAAAAAAAHwAAABUAAAAVAAAAFQAAABUAAAAVAAAAEQAAAAAAA + + 
'AAAOAAAAEQAAAAEAAAAGAAAAEQAAABEAAAAOAAAAAAAAABkAAAAVAAAAFQAA' + 
'ABkAAAAAAAEQAAABEAAAAAAAAAHgAAABEAAAARAAAAHgAAABAAAAAQAAAA' + 
'EAAAAAAAAAeAAAAEQAAABEAAAAeAAAAEQAAABEAAAAeAAAAAAAAABEAAAAV' + 
'AAAAFQAAAA4AAAAVAAAAFQAAABEAAAAAAAAAEAAAAAgAAAAEAAAACgAAABEA' + 
'AAARAAAAEQAAAAAAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAfAAAAAAAAA' + 
'AA4AAAARAAAAEAAAABAAAAAQAAAAEQAAAA4AAAAAAAAAEAAAABAAAAAQAAAA' + 
'HgAAABEAAAARAAAAHgAAAAAAAAARAAAACQAAAAAAAAPAAAAEQAAABEAAAAP' + 
'AAAAAAAABEAAAARAAAAEQAAABEAAAARAAAAEQAAAB8AAAAAAAAADgAAABEA' + 
'AAARAAAAEQAAABEAAAARAAAADgAAAAAAAAARAAAAEQAAABEAAAAfAAAAEQAA' + 
'ABEAAAARAAAAAAAAABEAAAARAAAAEQAAABUAAAAVAAAAGwAAABEAAAAAAAAA' + 
'CQAAAAKAAAAJAAAACQAAAAkAAAAJAAAABwAAAAAAAAARAAAAEgAAABQAAAAY' + 
'AAAAFAAAABIAAAARAAAAAAAAABEAAAARAAAAGQAAABUAAAATAAAAEQAAABUA' + 
'AAAAAAAEQAAABEAAAAZAAAAFQAAABMAAAARAAAAEQAAAAAAAAARAAAAEQAA' + 
'AAoAAAAEAAAACgAAABEAAAARAAAAAAAAABAAAAAQAAAAEAAAABAAAAAQAAAA' + 
'EQAAAB8AAAAAAAAABAAAAAQAAAAfAAAAFQAAABUAAAAfAAAABAAAAAAAAAAf' + 
'AAAAEAAAABAAAAAeAAAAEAAAABAAAAAfAAAAAAAAABEAAAAfAAAACgAAAAoA' + 
'AAAKAAAACgAAAAYAAAAAAAAAAQAAAB8AAAASAAAAEgAAABIAAAASAAAAEgAA' + 
'АААААААААААЕКАААБЕААААААААААААБАААААФАААААААААБАААААААА + + 
'HwAAABEAAAARAAAACgAAAAQAAAAAAAAAEgAAABUAAAAVAAAAHQAAABUAAAAV' + 
'ААААЕгАААААААААфАААААААААААААААААААААААААААААААААААААААААААА + + 
'AAAAAAAAAAAAAAAAAAAAAAAEQAAAA4AAAAAAAAADgAAAAIAAAACAAAAAgAA' + 
'AAIAAAACAAAADgAAAAAAAAAAAAAAAQAAAAIAAAAEAAAACAAAABAAAAAAAAAA' + 
'AAAAAA4AAAAIAAAACAAAAAgAAAAIAAAACAAAAA4AAAAAAAAAHwAAABAAAAAI' + 
'AAAADgAAAAIAAAABAAAAHwAAAAAAAAAEAAAABAAAAAQAAAAEAAAACgAAABEA' + 
'AAARAAAAAAAABEAAAARAAAACgAAAAQAAAAKAAAAEQAAABEAAAAAAAAACgAA' + 
'ABUAAAAVAAAAFQAAABEAAAARAAAAEQAAAAAAAAAEAAAABAAAAAoAAAAKAAAA' + 
'EQAAABEAAAARAAAAAAAAAA4AAAARAAAAEQAAABEAAAARAAAAEQAAABEAAAAA' + 
'AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAHwAAAAAAAAAOAAAAEQAAAAEA' + 
'AAAOAAAAEAAAABEAAAAOAAAAAAAAABEAAAASAAAAFAAAAB4AAAARAAAAEQAA' + 
'AB4AAAAAAAADQAAABIAAAAVAAAAEQAAABEAAAARAAAADgAAAAAAAAAQAAAA' + 
'EAAAABAAAAAeAAAAEQAAABEAAAAeAAAAAAAAAA4AAAARAAAAEQAAABEAAAAR' + 
'AAAAEQAAAA4AAAAAAAAAEQAAABEAAAATAAAAFQAAABkAAAARAAAAEQAAAAAA' + 
'AAARAAAAEQAAABEAAAAVAAAAFQAAABsAAAARAAAAAAAAAB8AAAARAAAAEAAA' + 
'АБАААААКААААААААБААААААААААЕКАААБИАААУААААГААААБКАААААААА + + 
'EQAAAAAAAAAOAAAAEQAAABEAAAABAAAAAQAAAAEAAAABAAAAAAAAAA4AAAAE' + 
'AAAABAAAAAQAAAAEAAAABAAAAA4AAAAAAAAAEQAAABEAAAARAAAAHwAAABEA' + 
'AAARAAAAEQAAAAAAAAAPAAAAEQAAABMAAAAQAAAAEAAAABEAAAAOAAAAAAAA' + 
'ABAAAAAQAAAAEAAAAB4AAAAQAAAAEAAAAB8AAAAAAAAAHwAAABAAAAAQAAAA' + 
'HgAAABAAAAAQAAAAHwAAAAAAAAAeAAAACQAAAAkAAAAJAAAACQAAAAkAAAAe' + 
'AAAAAAAAA4AAAARAAAAEAAAABAAAAAQAAAAEQAAAA4AAAAAAAAAHgAAABEA' + 
'AAARAAAHgAAABEAAAARAAAAHgAAAAAAAAARAAAAEQAAAB8AAAARAAAAEQAA' + 
'AAoAAAAEAAAAAAAAAA4AAAAQAAAAFwAAABUAAAATAAAAEQAAAA4AAAAAAAAA' + 
'BAAAAAAAAAEAAAAAgAAAAEAAAARAAAADgAAAAAAAAAIAAAABAAAAAIAAAAB' + 
'AAAAAgAAAAQAAAAIAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAfAAAAAAAAAAAAA + + 
'AAAAAAAAAgAAAAQAAAAIAAAAEAAAAAgAAAAEAAAAAgAAAAAAAAAIAAAABAAA' + 
'AAwAAAAMAAAAAAAAAAwAAAAMAAAAAAAAAAwAAAAMAAAAAAAAAAAAAAAMAAAA' + 
'DAAAAAAAAAAAAAAHAHAAAAIAAAABAAAADwAAABEAAAARAAAADgAAAAAAAAAO' + 
'AAAAEQAAABEAAAAOAAAAEQAAABEAAAAOAAAAAAAAAAgAAAAIAAAACAAAAAQA' + 
'AAACAAAAAQAAAB8AAAAAAAAADgAAABEAAAARAAAAHgAAABAAAAAIAAAABwAA' + 
'AAAAAAAOAAAAEQAAAAEAAAABAAAAHgAAABAAAAAfAAAAAAAAAAIAAAACAAAA' + 
'HwAAABIAAAAKAAAABgAAAAIAAAAAAAAADgAAABEAAAABAAAABgAAAAIAAAAB' + 
'AAAAHwAAAAAAAAAfAAAAEAAAAAgAAAAGAAAAAQAAABEAAAAOAAAAAAAAAA4A' + 
'AAAEAAAABAAAAAQAAAAEAAAADAAAAAQAAAAAAAAADgAAABEAAAAZAAAAFQAA' + 
'ABMAAAARAAAADgAAAAAAAAAAAAAAEAAAAAgAAAAEAAAAAgAAAAEAAAAAAAAA' + 
'ААААААВААААМААААААААААААААААААААААААААААААААААААААААААААААА' + 
'AAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAwAAAAMAAAAAAAAAAAA' + 
'ААААААААААААААААААЕАААБААААБ8ААААААААБААААААААААААААААААА' + 
'AAQAAAAVAAAADgAAABUAAAAEAAAAAAAAAAAAAAAIAAAABAAAAAIAAAACAAAA' + 
'AgAAAAQAAAAIAAAAAAAAAAIAAAAEAAAACAAAAAgAAAAIAAAABAAAAAIAAAAA' + 
'АААААААААААААААААААБАААААИАААГААААБгАААААААААНААААегАААБУА' + 
'AAAMAAAACgAAAAoAAAAEAAAAAAAAAAMAAAATAAAACAAAAAQAAAACAAAAGQAA' + 
'ABgAAAAAAAABAAAAB4AAAAFAAAADgAAABQAAAAPAAAABAAAAAAAAAAKAAAA' + 
'CgAAAB8AAAAKAAAAHwAAAAoAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK' + 
'AAAACgAAAAoAAAAAAAAABAAAAAAAAAAEAAAABAAAAAQAAAAEAAAABAAAAAAAA + + 
'ААААААААААААААААААААААААААААААААААААААААААААААААААААААААААА + + 
'AAAAAAAAAAAAAAAAAAAAAAFAAAABQAAAAUAAAA9AAAAJwAAACAAAAAgAAAA' + 
'OAAAAAQAAAAMAAAAHQAAAD8AAAA / AAAAHQAAAAwAAAAEAAAAAAAAAAAAAAAA' + 
'AAAAPwAAAD8AAAAAAAAAAAAAAAAAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwA' + 
'АААМААААДАААААААААААААААААААААААААААААААААААААААААААААААААА' + 
'ААААААААААААААААААААААААААААААААААААААААААААААААААААААААААА + + 
'AAAAAAAAAAAAAAAAAAAAD8AAAA / AAAAPwAAAD8AAAA / AAAAPwAAAD8AAAA /' + 
'AAAAPwAAAD8AAAA / AAAAPwAAAAcAAAAHAAAABwAAAAcAAAA / AAAAPwAAAD8A' + 
'AAA / AAAAOAAAADgAAAA4AAAAOAAAAD8AAAA / AAAAPwAAAD8AAAAAAAAAAAAA' + 
'AAAAAAAAAAAOAAAADgAAAA4AAAAOAAAAD8AAAA / AAAAPwAAAD8AAAA4AAAA' + 
'OAAAADgAAAA4AAAABwAAAAcAAAAHAAAABwAAADgAAAA4AAAAOAAAADgAAAA4' + 
'AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAAAAAAAAAAAAAAAAAAAAAA' + 
'AAAMAAAAHgAAAD8AAAAMAAAADAAAAAwAAAAMAAAADAAAAAgAAAAMAAAALgAA' + 
'AD8AAAA / AAAALgAAAAwAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' + 
'ААААААААААААААААААААААААААААААААААААААААААААААААААААВАААААМ' + 
'AAAADAAAAAwAAAAMAAAAPwAAAB4AAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' + 
'AAAAAAAAAAAAAAAAAAhAAAAEgAAAAwAAAAMAAAALQAAAD8AAAAMAAAADAAA' + 
'АААААААААААААААААААААААААААААААААААААААААААБАААААААААААААА + + 
'BwAAAD8AAAA / AAAAPwAAAD8AAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAH' + 
'AAAABwAAAAcAAAAHAAAABwAAAAcAAAA4AAAAOAAAADgAAAA4AAAABwAAAAcA' + 
'АААХАААБВАААААААААААААААААААААААААААААААААААААААААААААПВАА' + 
'AD8AAAA / AAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABwAAAAcAAAAHAAAA' + 
'ААААААААААААААААААААДГАААА4ААААОААААДГААААААААААААААААААААА' + 
'AAAAAAAAAAAAAAAAAAAAAAAAAA ==';
}
